# Generated by Django 4.1.2 on 2022-12-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='precio',
            field=models.CharField(default=12, max_length=10, verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
